export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOG_OUT = "LOG_OUT";
export const LOAD_PROFILE = "LOAD_PROFILE";

export const HOME_VID_REQUEST = "HOME_VID_REQUEST";
export const HOME_VID_SUCCESS = "HOME_VID_SUCCESS";
export const HOME_VID_FAIL = "HOME_VID_FAIL";

export const VIDEO_SEARCH_REQUEST = "VIDEO_SEARCH_REQUEST";
export const VIDEO_SEARCH_SUCCESS = "VIDEO_SEARCH_SUCCESS";
export const VIDEO_SEARCH_FAIL = "VIDEO_SEARCH_FAIL";

export const CHANNEL_DETAILS_REQUEST = "CHANNEL_DETAILS_REQUEST";
export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_DETAILS_SUCCESS";
export const CHANNEL_DETAILS_FAIL = "CHANNEL_DETAILS_FAIL";

export const RELATED_VIDEOS_REQUEST = "RELATED_VIDEOS_REQUEST";
export const RELATED_VIDEOS_SUCCESS = "RELATED_VIDEOS_SUCCESS";
export const RELATED_VIDEOS_FAIL = "RELATED_VIDEOS_FAIL";
